import { useMemo } from 'react';
import { ArrowUpRight, BusFront, Check, ChevronRight, CircleAlert, LocateFixed, Minus, Plus, RefreshCw, ShieldCheck } from 'lucide-react';
import { Link } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { getGetBusLocationQueryKey, getGetBusQueryKey, getGetQueueStatusQueryKey, getListBusesQueryKey, getListNotificationsQueryKey, useGetBus, useGetBusLocation, useGetQueueStatus, useListBuses, useListNotifications, useUpdateBusOccupancy } from '@workspace/api-client-react';
import { BusMiniRoute, EmptyState, ErrorState, formatUpdatedAt, LoadingRows, OccupancyBar, PageHeading, statusLabel, useSelectedBusId } from '@/components/acims-ui';

export default function Dashboard() {
  const queryClient = useQueryClient();
  const selectedBusId = useSelectedBusId();
  const busesQuery = useListBuses({ query: { queryKey: getListBusesQueryKey(), refetchInterval: 30000 } });
  const bus = useMemo(() => busesQuery.data?.find((item) => item.id === selectedBusId) ?? busesQuery.data?.[0], [busesQuery.data, selectedBusId]);
  const busId = bus?.id ?? '';
  const busQuery = useGetBus(busId, { query: { enabled: !!busId, queryKey: getGetBusQueryKey(busId), refetchInterval: 30000 } });
  const locationQuery = useGetBusLocation(busId, { query: { enabled: !!busId, queryKey: getGetBusLocationQueryKey(busId), refetchInterval: 30000 } });
  const queueQuery = useGetQueueStatus({ busId }, { query: { enabled: !!busId, queryKey: getGetQueueStatusQueryKey({ busId }) } });
  const notificationsQuery = useListNotifications({ query: { queryKey: getListNotificationsQueryKey() } });
  const occupancyMutation = useUpdateBusOccupancy();
  const activeBus = busQuery.data ?? bus;
  const latestAlert = notificationsQuery.data?.[0];
  if (busesQuery.isLoading) return <DashboardSkeleton />;
  if (busesQuery.isError) return <ErrorState onRetry={() => void busesQuery.refetch()} label="The route board is taking a moment to reconnect." />;
  if (!activeBus) return <EmptyState icon={BusFront} title="No campus buses are moving yet" message="When service starts, your selected route will appear here with a live arrival estimate." />;
  const location = locationQuery.data;
  const queue = queueQuery.data;
  return <div className="page-in">
    <PageHeading eyebrow="Wednesday · 8:14 AM" title="Make the next move." description="Your commute, without the guessing. This is the latest read from the campus fleet." action={<Link href="/map" data-testid="link-open-live-map" className="inline-flex items-center gap-2 rounded-full bg-primary px-4 py-2.5 text-xs font-extrabold text-primary-foreground transition hover:-translate-y-0.5 hover:shadow-lg">Open live map <ArrowUpRight size={15} /></Link>} />
    <section className="grid gap-4 xl:grid-cols-[1.5fr_1fr]">
      <div className="overflow-hidden rounded-[28px] bg-primary p-6 text-primary-foreground soft-shadow sm:p-8">
        <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mono text-[10px] uppercase tracking-[0.18em] text-primary-foreground/55">Selected ride</div><div className="mt-2 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-accent text-accent-foreground"><BusFront size={23} /></span><div><h2 className="display-font text-2xl font-extrabold">Bus {activeBus.busNumber}</h2><BusMiniRoute bus={activeBus} /></div></div></div><span className="flex items-center gap-2 rounded-full bg-primary-foreground/10 px-3 py-1.5 text-[11px] font-bold"><span className="pulse-dot h-2 w-2 rounded-full bg-accent" /> {statusLabel(location?.status ?? activeBus.status)}</span></div>
        <div className="mt-12 flex items-end gap-5"><div><div className="mono text-[11px] uppercase tracking-[0.16em] text-primary-foreground/55">Arriving in</div><div className="display-font mt-1 text-[5.5rem] font-extrabold leading-none tracking-[-0.11em] text-accent">{location?.etaMinutes ?? activeBus.etaMinutes}<span className="ml-2 text-2xl tracking-normal text-primary-foreground/70">min</span></div></div><div className="mb-2 border-l border-primary-foreground/15 pl-5"><div className="text-sm font-extrabold">{location?.nextStop ?? activeBus.nextStop}</div><div className="mt-1 text-xs text-primary-foreground/55">next stop</div></div></div>
        <div className="mt-8 grid gap-5 border-t border-primary-foreground/15 pt-5 sm:grid-cols-2"><div><OccupancyBar occupancy={activeBus.currentOccupancy} capacity={activeBus.capacity} /></div><div className="flex items-center gap-2 text-xs text-primary-foreground/60"><LocateFixed size={15} className="text-accent" /> Signal updated {formatUpdatedAt(location?.updatedAt ?? activeBus.updatedAt)}<span className="ml-auto text-[10px] uppercase tracking-wider">GPS</span></div></div>
        <div className="mt-5 flex flex-wrap items-center gap-2 border-t border-primary-foreground/15 pt-4"><span className="mono mr-auto text-[10px] uppercase tracking-[0.14em] text-primary-foreground/45">Demo occupancy control</span><button type="button" aria-label="Remove one rider" disabled={occupancyMutation.isPending || activeBus.currentOccupancy === 0} onClick={() => { occupancyMutation.mutate({ busId: activeBus.id, data: { currentOccupancy: activeBus.currentOccupancy - 1 } }, { onSuccess: () => { void queryClient.invalidateQueries({ queryKey: getListBusesQueryKey() }); void queryClient.invalidateQueries({ queryKey: getGetBusQueryKey(activeBus.id) }); void queryClient.invalidateQueries({ queryKey: getGetQueueStatusQueryKey({ busId: activeBus.id }) }); void queryClient.invalidateQueries({ queryKey: getListNotificationsQueryKey() }); } }); }} className="grid h-8 w-8 place-items-center rounded-lg border border-primary-foreground/20 text-primary-foreground transition hover:bg-primary-foreground/10 disabled:opacity-40"><Minus size={14} /></button><span className="min-w-[64px] text-center text-[11px] font-extrabold text-primary-foreground/70">{activeBus.currentOccupancy}/{activeBus.capacity}</span><button type="button" aria-label="Add one rider" disabled={occupancyMutation.isPending || activeBus.currentOccupancy === activeBus.capacity} onClick={() => { occupancyMutation.mutate({ busId: activeBus.id, data: { currentOccupancy: activeBus.currentOccupancy + 1 } }, { onSuccess: () => { void queryClient.invalidateQueries({ queryKey: getListBusesQueryKey() }); void queryClient.invalidateQueries({ queryKey: getGetBusQueryKey(activeBus.id) }); void queryClient.invalidateQueries({ queryKey: getGetQueueStatusQueryKey({ busId: activeBus.id }) }); void queryClient.invalidateQueries({ queryKey: getListNotificationsQueryKey() }); } }); }} className="grid h-8 w-8 place-items-center rounded-lg border border-primary-foreground/20 text-primary-foreground transition hover:bg-primary-foreground/10 disabled:opacity-40"><Plus size={14} /></button></div>
      </div>
      <div className="rounded-[28px] border border-border bg-card p-6 soft-shadow sm:p-8"><div className="flex items-center justify-between"><div><div className="mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Boarding outlook</div><h2 className="mt-2 display-font text-2xl font-extrabold">{queue?.seatsAvailable ?? Math.max(0, activeBus.capacity - activeBus.currentOccupancy)} seats open</h2></div><div className="grid h-11 w-11 place-items-center rounded-2xl bg-secondary text-secondary-foreground"><ShieldCheck size={21} /></div></div><p className="mt-5 text-sm leading-6 text-muted-foreground">{queue?.message ?? 'Live capacity is estimated from the latest bus count.'}</p><div className="mt-6 space-y-3 border-t border-border pt-5 text-xs"><div className="flex justify-between"><span className="text-muted-foreground">Your queue</span><span className={`font-extrabold ${queue?.joined ? 'text-foreground' : 'text-muted-foreground'}`}>{queue?.joined ? `Position ${queue.entry?.queuePosition ?? '—'}` : 'Not joined'}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Likely availability</span><span className="font-extrabold">{queue?.estimatedAvailabilityMinutes ?? 0} min</span></div></div><Link href="/queue" data-testid="link-manage-queue" className="mt-6 flex items-center justify-between rounded-xl bg-muted px-4 py-3 text-xs font-extrabold transition hover:bg-secondary">Manage boarding queue <ChevronRight size={15} /></Link></div>
    </section>
    <section className="mt-5 grid gap-4 md:grid-cols-[1.25fr_.75fr]">
      <div className="rounded-[24px] border border-border bg-card p-6"><div className="flex items-center justify-between"><div><div className="mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Route pulse</div><h2 className="mt-2 text-lg font-extrabold">On the way to {activeBus.destination}</h2></div><Link href="/map" data-testid="link-route-pulse-map" className="rounded-full border border-border p-2 text-muted-foreground transition hover:bg-muted"><ArrowUpRight size={16} /></Link></div><div className="mt-8 flex items-center gap-2 text-xs font-bold"><span className="h-3 w-3 rounded-full bg-secondary ring-4 ring-secondary/20" /><span>{activeBus.origin}</span><span className="h-px flex-1 bg-border" /><span className="h-3 w-3 rounded-full bg-accent-foreground ring-4 ring-accent/40" /><span>{location?.nextStop ?? activeBus.nextStop}</span><span className="h-px flex-1 bg-border" /><span className="h-3 w-3 rounded-full border-2 border-muted-foreground" /><span>{activeBus.destination}</span></div><div className="mt-3 flex justify-between text-[10px] text-muted-foreground"><span>Departed</span><span>Next stop</span><span>End of line</span></div></div>
      <div className={`rounded-[24px] border p-6 ${latestAlert ? 'border-destructive/25 bg-destructive/10' : 'border-border bg-card'}`}><div className="flex items-center gap-2 text-xs font-extrabold"><CircleAlert size={16} className={latestAlert ? 'text-destructive' : 'text-muted-foreground'} /> Latest service note</div>{notificationsQuery.isLoading ? <div className="mt-4 skeleton h-12 rounded-lg" /> : latestAlert ? <><h3 className="mt-4 text-sm font-extrabold">{latestAlert.title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{latestAlert.message}</p><Link href="/alerts" data-testid="link-latest-alert" className="mt-4 inline-flex items-center gap-1 text-xs font-extrabold">Read all alerts <ArrowUpRight size={14} /></Link></> : <p className="mt-4 text-sm leading-6 text-muted-foreground">No service notes for your route. Keep moving.</p>}</div>
    </section>
    <div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><RefreshCw size={13} /> Auto-refreshes every 30 seconds <span className="text-border">·</span> <Check size={13} className="text-secondary-foreground" /> Read from live operations</div>
  </div>;
}

function DashboardSkeleton() {
  return <div className="page-in"><div className="skeleton mb-8 h-24 w-3/4 rounded-2xl" /><div className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><div className="skeleton h-[370px] rounded-[28px]" /><div className="skeleton h-[370px] rounded-[28px]" /></div><div className="mt-5"><LoadingRows count={2} /></div></div>;
}