import { useState } from 'react';
import { ArrowRight, BusFront, Clock3, ExternalLink, Radio, Route as RouteIcon, Search, TrainFront } from 'lucide-react';
import { useListBuses, getListBusesQueryKey, getListTransportProvidersQueryKey, useListTransportProviders, useSearchTransport } from '@workspace/api-client-react';
import { EmptyState, ErrorState, LoadingRows, PageHeading } from '@/components/acims-ui';

export default function PublicTransportPage() {
  const providersQuery = useListTransportProviders({ query: { queryKey: getListTransportProvidersQueryKey() } });
  const busesQuery = useListBuses({ query: { queryKey: getListBusesQueryKey() } });
  const searchMutation = useSearchTransport();
  const [start, setStart] = useState('');
  const [destination, setDestination] = useState('');
  const providers = providersQuery.data ?? [];
  const journeys = searchMutation.data ?? [];
  const search = () => { if (start.trim() && destination.trim()) searchMutation.mutate({ data: { start: start.trim(), destination: destination.trim() } }); };
  const loading = providersQuery.isLoading || busesQuery.isLoading;
  if (loading) return <LoadingRows count={5} />;
  if (providersQuery.isError || busesQuery.isError) return <ErrorState onRetry={() => { void providersQuery.refetch(); void busesQuery.refetch(); }} label="Transport provider status could not be loaded." />;
  return <div className="page-in">
    <PageHeading eyebrow="Beyond campus" title="Compare the wider trip." description="Search public transport alongside the ACIMS college bus. External journeys are clearly marked when they are development data." action={<div className="rounded-full border border-border bg-card px-3 py-2 text-[11px] font-bold"><Radio size={13} className="mr-1 inline text-accent-foreground" /> Provider status</div>} />
    <section className="rounded-[28px] border border-border bg-card p-5 sm:p-7"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="text-xs font-extrabold">Start<input data-testid="input-transport-start" value={start} onChange={(event) => setStart(event.target.value)} placeholder="College, residence, gate…" className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-3 text-sm font-medium outline-none focus:ring-2 focus:ring-ring" /></label><label className="text-xs font-extrabold">Destination<input data-testid="input-transport-destination" value={destination} onChange={(event) => setDestination(event.target.value)} placeholder="Where are you going?" className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-3 text-sm font-medium outline-none focus:ring-2 focus:ring-ring" /></label><button type="button" data-testid="button-search-transport" onClick={search} disabled={searchMutation.isPending || !start.trim() || !destination.trim()} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-accent px-5 text-sm font-extrabold text-accent-foreground disabled:opacity-50">{searchMutation.isPending ? 'Searching…' : <><Search size={16} /> Search journeys</>}</button></div>{searchMutation.isError && <p className="mt-3 text-xs font-bold text-destructive">The external journey search is unavailable right now. ACIMS college-bus context is still shown below.</p>}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
      <div className="rounded-[28px] border border-border bg-card p-6"><div className="mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Provider health</div><h2 className="mt-2 text-2xl font-extrabold">Who is reporting?</h2><div className="mt-5 space-y-2">{providers.length ? providers.map((provider) => <div key={provider.id} data-testid={`row-provider-${provider.id}`} className="flex items-center gap-3 rounded-xl bg-muted p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-card"><Radio size={14} /></span><span className="flex-1"><span className="block text-xs font-extrabold">{provider.name}</span><span className="text-[10px] text-muted-foreground">{provider.category} · {provider.dataLabel}</span></span><span className={`rounded-full px-2 py-1 text-[9px] font-extrabold ${provider.status.toLowerCase().includes('online') ? 'bg-secondary' : 'bg-destructive/15 text-destructive'}`}>{provider.status}</span></div>) : <EmptyState icon={Radio} title="No providers listed" message="Provider status is not available." />}</div></div>
      <div className="space-y-5">
        <div className="rounded-[28px] border border-border bg-card p-6"><div className="flex items-center justify-between"><div><div className="mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">ACIMS college bus</div><h2 className="mt-2 text-2xl font-extrabold">Real campus options</h2></div><BusFront size={22} className="text-accent-foreground" /></div><div className="mt-5 space-y-2">{busesQuery.data?.length ? busesQuery.data.map((bus) => <div key={bus.id} data-testid={`card-college-bus-${bus.id}`} className="rounded-2xl border border-border p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary text-accent"><BusFront size={16} /></span><div className="flex-1"><div className="text-sm font-extrabold">Bus {bus.busNumber} · {bus.routeLabel}</div><div className="mt-1 text-[11px] text-muted-foreground">{bus.origin} → {bus.destination}</div></div><span className="rounded-full bg-accent px-2.5 py-1 text-[10px] font-extrabold">{bus.etaMinutes} min</span></div><div className="mt-3 flex items-center gap-3 text-[11px] font-bold text-muted-foreground"><Clock3 size={13} /> Next: {bus.nextStop}<span className="text-border">|</span>{bus.capacity - bus.currentOccupancy} seats available</div></div>) : <EmptyState icon={BusFront} title="No college buses active" message="There is no live ACIMS college-bus result to show right now." />}</div></div>
        {journeys.length > 0 && <div className="rounded-[28px] border border-border bg-card p-6"><div className="flex items-center justify-between"><div><div className="mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Search results</div><h2 className="mt-2 text-2xl font-extrabold">Wider trip options</h2></div><span className="rounded-full bg-destructive/15 px-2.5 py-1 text-[9px] font-extrabold text-destructive">DEVELOPMENT / MOCK EXTERNAL DATA</span></div><div className="mt-5 space-y-2">{journeys.map((journey) => <div key={journey.id} data-testid={`card-external-journey-${journey.id}`} className="rounded-2xl border border-border p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-muted"><TrainFront size={16} /></span><div className="flex-1"><div className="text-sm font-extrabold">{journey.route}</div><div className="mt-1 text-[11px] text-muted-foreground">{journey.departure} → {journey.arrival} · {journey.durationMinutes} min</div></div><ExternalLink size={15} className="text-muted-foreground" /></div><div className="mt-3 flex flex-wrap items-center gap-2 text-[10px] font-bold text-muted-foreground"><span>{journey.transfers} transfers</span><span>·</span><span>{journey.walkingDistanceKm.toFixed(1)} km walk</span><span>·</span><span>{journey.availability}</span><span className="rounded-full bg-destructive/10 px-2 py-1 text-destructive">{journey.dataLabel || 'DEVELOPMENT / MOCK EXTERNAL DATA'}</span></div></div>)}</div></div>}
        {!journeys.length && !searchMutation.isPending && <div className="rounded-[28px] border border-dashed border-border bg-card p-6 text-center"><RouteIcon size={22} className="mx-auto text-muted-foreground" /><p className="mt-3 text-sm font-extrabold">Search for a wider journey</p><p className="mt-1 text-xs text-muted-foreground">Results will appear with their data source and freshness label.</p></div>}
      </div>
    </section>
  </div>;
}