import { useState } from 'react';
import { AlertTriangle, CheckCircle2, LocateFixed, PhoneCall, ShieldAlert, Siren } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { demoStudentId, EmptyState, ErrorState, LoadingRows, PageHeading } from '@/components/acims-ui';
import { getListSafetyAlertsQueryKey, getListSafetyReportsQueryKey, useActivateEmergency, useCreateSafetyReport, useListSafetyAlerts, useListSafetyReports } from '@workspace/api-client-react';

const COLLEGE_CENTER = { latitude: 12.9055, longitude: 80.0918 };

export default function SafetyPage() {
  const queryClient = useQueryClient();
  const alertsQuery = useListSafetyAlerts({ query: { queryKey: getListSafetyAlertsQueryKey() } });
  const reportsQuery = useListSafetyReports({ query: { queryKey: getListSafetyReportsQueryKey() } });
  const reportMutation = useCreateSafetyReport();
  const emergencyMutation = useActivateEmergency();
  const [reportType, setReportType] = useState('lighting');
  const [description, setDescription] = useState('');
  const [location, setLocation] = useState(COLLEGE_CENTER);
  const [locationNote, setLocationNote] = useState('College coordinates');
  const [emergencyMessage, setEmergencyMessage] = useState('I need assistance on campus.');
  const [emergencyResult, setEmergencyResult] = useState<{ message: string; contacts: Array<{ name: string; relationship: string; phone: string }> }>();
  const alerts = alertsQuery.data ?? [];
  const reports = reportsQuery.data ?? [];
  const refresh = () => { void alertsQuery.refetch(); void reportsQuery.refetch(); };
  const locate = () => {
    if (!navigator.geolocation) { setLocationNote('Browser location unavailable · using College coordinates'); return; }
    navigator.geolocation.getCurrentPosition((position) => { setLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude }); setLocationNote('Using browser location'); }, () => setLocationNote('Location permission unavailable · using College coordinates'));
  };
  const submitReport = () => {
    if (!description.trim()) return;
    reportMutation.mutate({ data: { studentId: demoStudentId, reportType, description: description.trim(), latitude: location.latitude, longitude: location.longitude } }, { onSuccess: () => { setDescription(''); refresh(); void queryClient.invalidateQueries({ queryKey: getListSafetyReportsQueryKey() }); } });
  };
  const activateEmergency = () => emergencyMutation.mutate({ data: { studentId: demoStudentId, latitude: location.latitude, longitude: location.longitude, message: emergencyMessage.trim() || 'I need assistance on campus.' } }, { onSuccess: (response) => setEmergencyResult(response) });
  const loading = alertsQuery.isLoading || reportsQuery.isLoading;
  const error = alertsQuery.isError || reportsQuery.isError;
  if (loading) return <LoadingRows count={5} />;
  if (error) return <ErrorState onRetry={refresh} label="Safety information could not be loaded." />;

  return <div className="page-in">
    <PageHeading eyebrow="Look out for one another" title="Safety, without guesswork." description="See active campus alerts, report what you notice, and reach configured contacts when you need support." action={<div className="flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2 text-[11px] font-bold"><ShieldAlert size={14} className="text-destructive" /> ACIMS safety desk</div>} />
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <div className="space-y-5">
        <div className="rounded-[28px] border border-border bg-card p-6 sm:p-8"><div className="flex items-center justify-between"><div><div className="mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Active alerts</div><h2 className="mt-2 text-2xl font-extrabold">What is happening nearby?</h2></div><span className="rounded-full bg-destructive/15 px-2.5 py-1 text-[10px] font-extrabold text-destructive">{alerts.length} active</span></div><div className="mt-5 space-y-3">{alerts.length ? alerts.map((alert) => <div key={alert.id} data-testid={`card-safety-alert-${alert.id}`} className="rounded-2xl border border-destructive/20 bg-destructive/5 p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-destructive/15 text-destructive"><AlertTriangle size={17} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-extrabold">{alert.title}</h3><span className="rounded-full bg-card px-2 py-1 text-[9px] font-extrabold uppercase">{alert.severity}</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{alert.message}</p><div className="mono mt-2 text-[9px] text-muted-foreground">{new Date(alert.createdAt).toLocaleString()}</div></div></div></div>) : <EmptyState icon={CheckCircle2} title="No active safety alerts" message="ACIMS has no current campus safety notices to share." />}</div></div>
        <div className="rounded-[28px] border border-border bg-card p-6 sm:p-8"><div className="mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Your reports</div><h2 className="mt-2 text-2xl font-extrabold">A record of what you raised.</h2><div className="mt-5 space-y-2">{reports.length ? reports.map((report) => <div key={report.id} data-testid={`row-safety-report-${report.id}`} className="flex items-start gap-3 rounded-xl bg-muted p-3"><span className="mt-0.5 h-2.5 w-2.5 rounded-full bg-accent-foreground" /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><span className="text-xs font-extrabold">{report.reportType}</span><span className="rounded-full bg-card px-2 py-1 text-[9px] font-extrabold">{report.status}</span></div><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{report.description}</p><div className="mono mt-1 text-[9px] text-muted-foreground">{new Date(report.createdAt).toLocaleString()}</div></div></div>) : <EmptyState icon={ShieldAlert} title="Nothing reported yet" message="Your submitted safety concerns will stay visible here." />}</div></div>
      </div>
      <div className="space-y-5">
        <div className="rounded-[28px] border border-border bg-card p-6 sm:p-8"><div className="mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Create a report</div><h2 className="mt-2 text-2xl font-extrabold">Tell the safety desk.</h2><label className="mt-6 block text-xs font-extrabold" htmlFor="report-type">Report type</label><select id="report-type" data-testid="select-report-type" value={reportType} onChange={(event) => setReportType(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="lighting">Lighting</option><option value="obstruction">Obstruction</option><option value="harassment">Harassment</option><option value="medical">Medical concern</option><option value="other">Other</option></select><label className="mt-4 block text-xs font-extrabold" htmlFor="report-description">Description</label><textarea id="report-description" data-testid="input-report-description" value={description} onChange={(event) => setDescription(event.target.value)} rows={4} placeholder="What should the safety desk know?" className="mt-2 w-full resize-none rounded-xl border border-input bg-background px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-ring" /><button type="button" data-testid="button-report-location" onClick={locate} className="mt-3 flex w-full items-center gap-2 rounded-xl border border-border px-3 py-3 text-left text-xs font-bold hover:bg-muted"><LocateFixed size={15} /><span className="flex-1">{locationNote}</span></button><button type="button" data-testid="button-submit-safety-report" onClick={submitReport} disabled={reportMutation.isPending || !description.trim()} className="mt-4 w-full rounded-xl bg-primary px-4 py-3.5 text-sm font-extrabold text-primary-foreground disabled:opacity-50">{reportMutation.isPending ? 'Sending to the safety desk…' : 'Submit safety report'}</button>{reportMutation.isError && <p className="mt-3 text-xs font-bold text-destructive">The report could not be sent. Try again.</p>}</div>
        <div className="rounded-[28px] bg-primary p-6 text-primary-foreground sm:p-8"><div className="flex items-start justify-between"><div><div className="mono text-[10px] uppercase tracking-[.18em] text-primary-foreground/55">Need help now?</div><h2 className="mt-2 text-2xl font-extrabold">Request emergency assistance.</h2></div><Siren size={22} className="text-accent" /></div><p className="mt-3 text-xs leading-5 text-primary-foreground/70">ACIMS can notify the configured contacts attached to your student profile.</p><textarea data-testid="input-emergency-message" value={emergencyMessage} onChange={(event) => setEmergencyMessage(event.target.value)} rows={2} className="mt-5 w-full resize-none rounded-xl border border-primary-foreground/15 bg-primary-foreground/10 px-3 py-3 text-sm text-primary-foreground outline-none placeholder:text-primary-foreground/40" /><button type="button" data-testid="button-activate-emergency" onClick={activateEmergency} disabled={emergencyMutation.isPending} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-destructive px-4 py-3.5 text-sm font-extrabold text-destructive-foreground disabled:opacity-50"><PhoneCall size={16} />{emergencyMutation.isPending ? 'Sending assistance request…' : 'Activate assistance'}</button><p className="mt-3 text-[10px] leading-4 text-primary-foreground/55">Emergency services were not contacted by ACIMS. If you are in immediate danger, call local emergency services directly.</p>{emergencyMutation.isError && <p className="mt-3 text-xs font-bold text-destructive">The assistance request could not be sent.</p>}{emergencyResult && <div className="mt-4 rounded-xl bg-primary-foreground/10 p-3 text-xs"><div className="font-extrabold">{emergencyResult.message}</div>{emergencyResult.contacts.length ? <div className="mt-2 space-y-1 text-primary-foreground/70">{emergencyResult.contacts.map((contact) => <div key={`${contact.name}-${contact.phone}`}>{contact.name} · {contact.relationship} · {contact.phone}</div>)}</div> : <div className="mt-2 text-primary-foreground/65">No configured contacts were returned.</div>}</div>}</div>
      </div>
    </section>
  </div>;
}